settings:
  # Gameplay settings which can change how game works
  gameplay:
    # Allow breaking blocks in creative mode with sword
    # This is defaulty disabled in the vanilla
    breaking_with_sword: false
    # Should ladder works same as vines?
    # Look at: https://imgur.com/a/UGGnaRb
    ladder_works_as_vine: false
    
    # This option can greatly improve performance in some situations,
    # but breaks compatibility with "stacker" plugins like UltimateStacker bcs isn't calling "ItemSpawnEvent" event
    stack_instantly_without_dropping_item: false
    stack_instantly_exps_without_spawning_orb: false
  
  # Small performance tweaks
  performance:
    # Chorus plant updating when destroyed connected plants
    chorus_plant: true
    # Updating of connected blocks (Stairs, glass panes, iron bars, etc.)
    # Can cause visual problems, We recommend leaving it on
    connected_blocks: true
    # Ticking of leaves
    tick_leaves: true
    # Block ticking
    # Tick nearby blocks - water, lava, gravel, sand...
    tick_nearby_blocks: true
    # Disable drops from tile entities in the Creative mode (Chests, Hoppers..)
    disable_tile_drops: false
    # Enable gamemode adventure "can destroy" blocks function
    # Disable this if you are not using these tags on the items (Can save some CPU usage - lookups)
    can_destroy_adventure_function: true
    # Should these tags only be lookup when the player is in adventure mode?
    can_destroy_only_in_adventure_function: true
    
  # Settings about plugin events, compatibility with other plugins, etc.
  plugins:
    # Sync BlockBreakEvent, PlayerInteractEvent & PlayerItemDamageEvent events with server to support other plugins
    syncEvent: true
  
# AntiNuke settings & invalid breaking
anticheat:
  # Maximum blocks destroyed in one server tick (20 ticks = 1s)
  destroyed_blocks_limit: 3
  # Maximum radius within player and block
  max_radius_within_block_and_player: 6.4
  
  # Actions in case of rule violations
  actions:
    kick_player: true
    broadcast_console: true
    # Permission asyncblockbreak.anticheat
    broadcast_admins: false